
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import guiswitcher

class gui:         
    def __init__ (self, switcher) :
        from pathlib import Path

        # from tkinter import *
        # Explicit imports to satisfy Flake8
        from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

        self.window = Tk()

        self.window.geometry("1440x1024")
        self.window.configure(bg = "#000000")
        self.switcher = switcher


        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\alexa\OneDrive\Desktop\Star Trek Explorers\Star-Trek-Explorers\build\assets\frame1")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        canvas = Canvas(
            self.window,
            bg = "#000000",
            height = 1024,
            width = 1440,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = canvas.create_image(
            719.0,
            492.0,
            image=image_image_1
        )

        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command= self.button_1_clicked,
            relief="flat"
        )
        button_1.place(
            x=472.0,
            y=640.0,
            width=252.0,
            height=96.0
        )

        entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            598.0,
            512.0,
            image=entry_image_1
        )
        self.entry_1 = Entry(
            bd=0,
            bg="#97CDFF",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_1.place(
            x=154.0,
            y=472.0,
            width=888.0,
            height=78.0
        )
        self.window.resizable(False, False)
        self.window.mainloop()

    def destroy(self): 
        self.window.destroy(),
        self.switcher.switch_to_frame_2(),

    def button_1_clicked (self):
        Entry = self.entry_1.get()
        self.destroy()
        self.switcher.switch_to_frame_2()
        print ("Button 1 Clicked"), print (Entry)
        import Main
        Main.newgame(Entry)
